export type MockServerData = {
  apartmentIds: string[];
  titles: string[];
  descriptions: string[];
  postDates: string[];
  cities: string[];
  previewImages: string[];
  images: string[];
  isPremium: string[];
  ratings: string[];
  propertyTypes: string[];
  numberOfRooms: string[];
  numberOfGuests: string[];
  prices: string[];
  amenities: string[];
  users: string[];
  userIds: string[];
  emails: string[];
  avatars: string[];
  userTypes: string[];
  passwords: string[];
  commentsAmount: string[];
};
